# This workflow will help you to produce an HTML extra test results report

name: Newman Run
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Release name'     
        required: true
        default: 'Sprint 1'
      tags:
        description: 'Test run name'
      runtype:
        type: choice
        description: 'Run type'
        required: true
        options: 
        - test
        - regression
jobs:
  global-go-api-sample:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
   # INstall Node on the runner
      - name: Install Node
        uses: actions/setup-node@v2
        with: 
          node-version: '16.x'
    
    # Install the newman
      - name: Install newman
        run: |
          npm install -g newman

      - name: Install qase reporter
        run: |
          npm install -g newman-reporter-qase
     
      - name: check run type
        with:
          variables: |
          PROJ: "${{ github.event.inputs.runtype }} == test ? "PCG" : "APIGO"

   # Run the POSTMAN collection
      - name: Run API Tests
          newman run PEAS.collectionPoC.json -e PEAS_QA.environment.json
          -r qase --reporter-qase-logging 
          --reporter-qase-projectCode ${{ env.PROJ }}
          --reporter-qase-apiToken 745a19ec6abd2f5412ad144d2d4547a313a602c4 
          --reporter-qase-runName "API test Execution"
          --reporter-qase-runName "${{github.event.inputs.logLevel}} - ${{github.event.inputs.tags}}


